name: Build on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install 7zip, pkgconfiglite, msys2
      run: |
        choco install -y 7zip
        choco install -y pkgconfiglite
        choco install -y msys2 || echo "Ignoring MSYS2 refreshenv warning"

    - name: Add MSYS2 to PATH
      shell: pwsh
      run: |
        echo "C:\tools\msys64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile --add-data "amazon_cookies.pkl;." --add-data "amazon_session_info.json;." Amazon_seller_selenium.py

    - name: List EXE output
      run: dir dist

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: amazon-seller-exe
        path: dist/*.exe
